// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyPlannerSoft.Data;

#nullable disable

namespace StudyPlannerSoft.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20241001184329_upgraded")]
    partial class upgraded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01H6N7NV1KTPB9QDZ7FYDJ3HHK",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "01H6N7NV1JHYY7N2NFDYX4ATAP",
                            Name = "Deputy",
                            NormalizedName = "DEPUTY"
                        },
                        new
                        {
                            Id = "01H6N7NV1YTMCV8YPZC7QQGGG7",
                            Name = "Lecturer",
                            NormalizedName = "LECTURER"
                        },
                        new
                        {
                            Id = "01H6N7NV18JWC8MYPXCVZR9WZW",
                            Name = "Faculty",
                            NormalizedName = "FACULTY"
                        },
                        new
                        {
                            Id = "01H6N7NV1MHQDXGNYH2HQT34V9",
                            Name = "Department",
                            NormalizedName = "DEPARTMENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "01H6N7NV2P1KCVKY7F6EJH0FAF",
                            RoleId = "01H6N7NV1KTPB9QDZ7FYDJ3HHK"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FavouriteColor")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01H6N7NV2P1KCVKY7F6EJH0FAF",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ab8f46f-8951-4329-8fc1-5d3fbdadddb0",
                            Email = "admin@viko.lt",
                            EmailConfirmed = true,
                            FavouriteColor = "Red",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@VIKO.LT",
                            NormalizedUserName = "ADMIN@VIKO.LT",
                            PasswordHash = "AQAAAAIAAYagAAAAEBvtSa0zj4tNuKex6TOaUliCEbcUmZLnk9CmyMCYHzbH+laOILjl2YiBHJgvxq++bQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "08cccd1c-0367-462c-b3b2-34856b61d634",
                            TwoFactorEnabled = false,
                            UserName = "admin@viko.lt"
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = "01J94P9ZSBF5ERJ37FGX8VAG0V",
                            Email = "a.kirdeikiene@eif.viko.lt",
                            FacultyId = "01J94P9ZSBF15R6M3336A9E9DQ",
                            Name = "Elektronikos ir kompiuterių inžinerijos katedra",
                            ShortName = "EKIK"
                        },
                        new
                        {
                            Id = "01J94P9ZSBNNYBHQF7E4QSK0RR",
                            Email = "t.liogiene@eif.viko.lt",
                            FacultyId = "01J94P9ZSBF15R6M3336A9E9DQ",
                            Name = "Informacinių sistemų katedra",
                            ShortName = "ISK"
                        },
                        new
                        {
                            Id = "01J94P9ZSB702Q8Z6WJZJ7NGZ8",
                            Email = "j.zailskas@eif.viko.lt",
                            FacultyId = "01J94P9ZSBF15R6M3336A9E9DQ",
                            Name = "Programinės įrangos katedra",
                            ShortName = "PĮK"
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Faculty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = "01J94P9ZSB7GAZJRJN8KSNEQF7",
                            Email = "administracija@atf.viko.lt",
                            Name = "Agrotechnologijų fakultetas",
                            ShortName = "ATF"
                        },
                        new
                        {
                            Id = "01J94P9ZSBESPDV9AJFN7ANA50",
                            Email = "administracija@dif.viko.lt",
                            Name = "Dizaino fakultetas",
                            ShortName = "DIF"
                        },
                        new
                        {
                            Id = "01J94P9ZSBF15R6M3336A9E9DQ",
                            Email = "info@eif.viko.lt",
                            Name = "Elektronikos ir informatikos fakultetas",
                            ShortName = "EIF"
                        },
                        new
                        {
                            Id = "01J94P9ZSBHDT978SGX5Y2BH6V",
                            Email = "administracija@ekf.viko.lt",
                            Name = "Ekonomikos fakultetas",
                            ShortName = "EKF"
                        },
                        new
                        {
                            Id = "01J94P9ZSBMVDE4MRR0TB2Q76W",
                            Email = "administracija@pdf.viko.lt",
                            Name = "Pedagogikos fakultetas",
                            ShortName = "PDF"
                        },
                        new
                        {
                            Id = "01J94P9ZSB6EX65NV4F27DZTZJ",
                            Email = "administracija@mtf.viko.lt",
                            Name = "Menų ir kūrybinių technologijų fakultetas",
                            ShortName = "MTF"
                        },
                        new
                        {
                            Id = "01J94P9ZSBT5GHB16SBQAR1614",
                            Email = "administracija@stf.viko.lt",
                            Name = "Statybos fakultetas",
                            ShortName = "STF"
                        },
                        new
                        {
                            Id = "01J94P9ZSBA81GE2SM964DD80Y",
                            Email = "info@spf.viko.lt",
                            Name = "Sveikatos priežiūros fakultetas",
                            ShortName = "SPF"
                        },
                        new
                        {
                            Id = "01J94P9ZSB8C8DQ6E4Z82GX2SR",
                            Email = "administracija@tef.viko.lt",
                            Name = "Technikos fakultetas",
                            ShortName = "TEF"
                        },
                        new
                        {
                            Id = "01J94P9ZSBC4RE2VMZ81VCW1F4",
                            Email = "administracija@vvf.viko.lt",
                            Name = "Verslo vadybos fakultetas",
                            ShortName = "VVF"
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Lecturer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.PlannedGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("LabelName")
                        .HasColumnType("text");

                    b.Property<string>("LecturerId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OtherType")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("StudyProgramId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubGroupCount")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("1");

                    b.Property<int?>("Vf")
                        .HasColumnType("integer");

                    b.Property<int?>("Vnf")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("PlannedGroups");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Pab")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = "01J94P9ZSB9GWC6VRT2JSH9Q0X",
                            Description = "Profesorius",
                            Name = "Profesorius_23",
                            Pab = 2.4199999999999999
                        },
                        new
                        {
                            Id = "01J94P9ZSB8QM217PQER5SJ3M5",
                            Description = "Docento, turinčio mokslo daktaro laipsnį",
                            Name = "Docentas_23",
                            Pab = 2.02
                        },
                        new
                        {
                            Id = "01J94P9ZSBFMSVQ6FKAN2E9KRH",
                            Description = "Docento, pripažinto menininko, o taip pat AT pritarimu vieneriems metams priimamam asmeniui, turinčiam didelę praktinę patirtį dėstomo dalyko srityje ir magistro kvalifikacinį laipsnį ar jam prilygintą aukštojo mokslo kvalifikaciją",
                            Name = "Docentas_menininkas_23",
                            Pab = 1.77
                        },
                        new
                        {
                            Id = "01J94P9ZSBQKMEE0DS40DQV3EA",
                            Description = "Lektoriaus, turinčio mokslo daktaro laipsnį",
                            Name = "Lektorius dr._23",
                            Pab = 1.72
                        },
                        new
                        {
                            Id = "01J94P9ZSBE7F048SQ2YBBYM04",
                            Description = "Lektorius",
                            Name = "Lektorius_23 (d)",
                            Pab = 1.6000000000000001
                        },
                        new
                        {
                            Id = "01J94P9ZSBXB7BE9B5G74HF4GJ",
                            Description = "Lektorius",
                            Name = "Lektorius_23 (m)",
                            Pab = 1.4299999999999999
                        },
                        new
                        {
                            Id = "01J94P9ZSB7Q4DCBYEN5PVCXTR",
                            Description = "Asistento, turinčio magistro laipsnį",
                            Name = "Asistentas_23 (mag.)",
                            Pab = 1.3300000000000001
                        },
                        new
                        {
                            Id = "01J94P9ZSB4M32ZR7DC5J58EM6",
                            Description = "Asistento, turinčio bakalauro arba profesinio bakalauro laipsnį",
                            Name = "Asistentas_23 (bak.)",
                            Pab = 1.3100000000000001
                        },
                        new
                        {
                            Id = "01J94P9ZSBR7RWJJQNSP77F60C",
                            Description = "Profesorius",
                            Name = "Profesorius_24",
                            Pab = 2.4199999999999999
                        },
                        new
                        {
                            Id = "01J94P9ZSBQTQ4D27NPDJTEKYZ",
                            Description = "Kviestinis profesorius",
                            Name = "Profesorius_Kv_24",
                            Pab = 2.4199999999999999
                        },
                        new
                        {
                            Id = "01J94P9ZSBDC2K7HX69EW0G6J0",
                            Description = "Docentas",
                            Name = "Docentas_24",
                            Pab = 2.02
                        },
                        new
                        {
                            Id = "01J94P9ZSBB1D67RF7RW0QP0X8",
                            Description = "Kviestinis docentas",
                            Name = "Docentas_Kv_24",
                            Pab = 2.02
                        },
                        new
                        {
                            Id = "01J94P9ZSBHTZK40XEQH4XX0PM",
                            Description = "Asistentas",
                            Name = "Asistentas_24",
                            Pab = 1.8400000000000001
                        },
                        new
                        {
                            Id = "01J94P9ZSB560T7A2SF2S5XRYX",
                            Description = "Jaunesnysis asistentas",
                            Name = "Jaunesnysis asistentas_24",
                            Pab = 1.78
                        },
                        new
                        {
                            Id = "01J94P9ZSBVHG5QMQD2Z81XMXR",
                            Description = "Vyresnysis lektorius",
                            Name = "Vyresnysis lektorius_24",
                            Pab = 1.72
                        },
                        new
                        {
                            Id = "01J94P9ZSB58CPSFVAQG72YQSQ",
                            Description = "Lektorius",
                            Name = "Lektorius_24",
                            Pab = 1.6000000000000001
                        },
                        new
                        {
                            Id = "01J94P9ZSBY2H9VZ5NR67FWM0J",
                            Description = "Dėstytojas praktikas",
                            Name = "Dėstytojas praktikas_24",
                            Pab = 1.72
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.StudyProgram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StudyType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("StudyPrograms");

                    b.HasData(
                        new
                        {
                            Id = "01J94P9ZSBV31MYJTE8WXWR9SX",
                            DepartmentId = "01J94P9ZSB702Q8Z6WJZJ7NGZ8",
                            Name = "Programinės įrangos testavimas",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J94P9ZSBR8QJB8EQDX93V8YG",
                            DepartmentId = "01J94P9ZSBF5ERJ37FGX8VAG0V",
                            Name = "Elektronikos inžinerija",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J94P9ZSBG676CAX8W0XRZA74",
                            DepartmentId = "01J94P9ZSBF5ERJ37FGX8VAG0V",
                            Name = "Elektronikos inžinerija",
                            StudyType = 2
                        },
                        new
                        {
                            Id = "01J94P9ZSBYE70GM84JPAJAJ7E",
                            DepartmentId = "01J94P9ZSBNNYBHQF7E4QSK0RR",
                            Name = "Informacijos sistemos",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J94P9ZSBCPCQ0WK5ZTZKPWPR",
                            DepartmentId = "01J94P9ZSBNNYBHQF7E4QSK0RR",
                            Name = "Informacijos sistemos",
                            StudyType = 2
                        },
                        new
                        {
                            Id = "01J94P9ZSB1DYZE8RVHK2P6S0H",
                            DepartmentId = "01J94P9ZSBNNYBHQF7E4QSK0RR",
                            Name = "Informacijos sistemos",
                            StudyType = 3
                        },
                        new
                        {
                            Id = "01J94P9ZSBZTY9Y446Q3WXZF2S",
                            DepartmentId = "01J94P9ZSBF5ERJ37FGX8VAG0V",
                            Name = "Kompiuterių inžinerija",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J94P9ZSBWEXMD1NMEGPVQN7W",
                            DepartmentId = "01J94P9ZSBF5ERJ37FGX8VAG0V",
                            Name = "Kompiuterių inžinerija",
                            StudyType = 2
                        },
                        new
                        {
                            Id = "01J94P9ZSB02N5AA8STSJXAANZ",
                            DepartmentId = "01J94P9ZSB702Q8Z6WJZJ7NGZ8",
                            Name = "Programų sistemos",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J94P9ZSBF27A3PS031W53SN6",
                            DepartmentId = "01J94P9ZSB702Q8Z6WJZJ7NGZ8",
                            Name = "Programų sistemos",
                            StudyType = 4
                        },
                        new
                        {
                            Id = "01J94P9ZSBGM9YV5T4997BKKW4",
                            DepartmentId = "01J94P9ZSB702Q8Z6WJZJ7NGZ8",
                            Name = "Programų sistemos",
                            StudyType = 2
                        },
                        new
                        {
                            Id = "01J94P9ZSBS63ZHNAMZJYKQN2T",
                            DepartmentId = "01J94P9ZSB702Q8Z6WJZJ7NGZ8",
                            Name = "Programų sistemos",
                            StudyType = 3
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("text");

                    b.Property<double>("ConsultationCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("CourseWorkHoursCount")
                        .HasColumnType("double precision");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("EvaluationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ExamHours")
                        .HasColumnType("double precision");

                    b.Property<double>("FinalProjectExamCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("GradingHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("GradingNumberCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeworkHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("LectureHours")
                        .HasColumnType("double precision");

                    b.Property<int>("LecturesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("OtherContactHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("OtherNonContactCount")
                        .HasColumnType("double precision");

                    b.Property<double>("PracticeHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("PracticeReportHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemoteLectureHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemotePracticeHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemoteTeachingHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("SelfStudyHours")
                        .HasColumnType("double precision");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("StudyProgramId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubGroupsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Department", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Lecturer", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Department", "Department")
                        .WithMany("Lecturers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyPlannerSoft.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.PlannedGroup", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Lecturer", "Lecturer")
                        .WithMany("PlannedGroups")
                        .HasForeignKey("LecturerId");

                    b.HasOne("StudyPlannerSoft.Entities.StudyProgram", "StudyProgram")
                        .WithMany("PlannedGroups")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.StudyProgram", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Department", "Department")
                        .WithMany("StudyPrograms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Subject", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.StudyProgram", "StudyProgram")
                        .WithMany("Subjects")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Department", b =>
                {
                    b.Navigation("Lecturers");

                    b.Navigation("StudyPrograms");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Lecturer", b =>
                {
                    b.Navigation("PlannedGroups");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.StudyProgram", b =>
                {
                    b.Navigation("PlannedGroups");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
