// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyPlannerSoft.Data;

#nullable disable

namespace StudyPlannerSoft.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20241002212349_PlansAdded")]
    partial class PlansAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LecturerSubject", b =>
                {
                    b.Property<string>("LecturersId")
                        .HasColumnType("text");

                    b.Property<string>("SubjectsId")
                        .HasColumnType("text");

                    b.HasKey("LecturersId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("SubjectLecturers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01H6N7NV1KTPB9QDZ7FYDJ3HHK",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "01H6N7NV1JHYY7N2NFDYX4ATAP",
                            Name = "Deputy",
                            NormalizedName = "DEPUTY"
                        },
                        new
                        {
                            Id = "01H6N7NV1YTMCV8YPZC7QQGGG7",
                            Name = "Lecturer",
                            NormalizedName = "LECTURER"
                        },
                        new
                        {
                            Id = "01H6N7NV18JWC8MYPXCVZR9WZW",
                            Name = "Faculty",
                            NormalizedName = "FACULTY"
                        },
                        new
                        {
                            Id = "01H6N7NV1MHQDXGNYH2HQT34V9",
                            Name = "Department",
                            NormalizedName = "DEPARTMENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "01H6N7NV2P1KCVKY7F6EJH0FAF",
                            RoleId = "01H6N7NV1KTPB9QDZ7FYDJ3HHK"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FavouriteColor")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01H6N7NV2P1KCVKY7F6EJH0FAF",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eae6b284-3d4b-4444-a836-2f2bc3d6028e",
                            Email = "admin@viko.lt",
                            EmailConfirmed = true,
                            FavouriteColor = "Red",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@VIKO.LT",
                            NormalizedUserName = "ADMIN@VIKO.LT",
                            PasswordHash = "AQAAAAIAAYagAAAAEG21+2isWFEYSSJLIuFmLrUT66vI7+vhdNbwQphTQgKDMI2zu6cIBOBzWEjD1Pa1Mw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "be1e084d-c40e-42ba-aeb2-92380774f49b",
                            TwoFactorEnabled = false,
                            UserName = "admin@viko.lt"
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = "01J97HWA49MJ8GASEX9J85VVZ3",
                            Email = "a.kirdeikiene@eif.viko.lt",
                            FacultyId = "01J97HWA49NPP50MA7RZT70CA6",
                            Name = "Elektronikos ir kompiuterių inžinerijos katedra",
                            ShortName = "EKIK"
                        },
                        new
                        {
                            Id = "01J97HWA49EV807R1NRT2W729H",
                            Email = "t.liogiene@eif.viko.lt",
                            FacultyId = "01J97HWA49NPP50MA7RZT70CA6",
                            Name = "Informacinių sistemų katedra",
                            ShortName = "ISK"
                        },
                        new
                        {
                            Id = "01J97HWA49EE1YW3XQJ9924XKW",
                            Email = "j.zailskas@eif.viko.lt",
                            FacultyId = "01J97HWA49NPP50MA7RZT70CA6",
                            Name = "Programinės įrangos katedra",
                            ShortName = "PĮK"
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Faculty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = "01J97HWA492QH629BXJTEF08EV",
                            Email = "administracija@atf.viko.lt",
                            Name = "Agrotechnologijų fakultetas",
                            ShortName = "ATF"
                        },
                        new
                        {
                            Id = "01J97HWA495FHD14K5DB1BS3XN",
                            Email = "administracija@dif.viko.lt",
                            Name = "Dizaino fakultetas",
                            ShortName = "DIF"
                        },
                        new
                        {
                            Id = "01J97HWA49NPP50MA7RZT70CA6",
                            Email = "info@eif.viko.lt",
                            Name = "Elektronikos ir informatikos fakultetas",
                            ShortName = "EIF"
                        },
                        new
                        {
                            Id = "01J97HWA49NJ7C05AT0EK8F1RD",
                            Email = "administracija@ekf.viko.lt",
                            Name = "Ekonomikos fakultetas",
                            ShortName = "EKF"
                        },
                        new
                        {
                            Id = "01J97HWA49QBEKMD7P0XNZSXYZ",
                            Email = "administracija@pdf.viko.lt",
                            Name = "Pedagogikos fakultetas",
                            ShortName = "PDF"
                        },
                        new
                        {
                            Id = "01J97HWA495SFWM5MXRPPVBT99",
                            Email = "administracija@mtf.viko.lt",
                            Name = "Menų ir kūrybinių technologijų fakultetas",
                            ShortName = "MTF"
                        },
                        new
                        {
                            Id = "01J97HWA49YFWB6DGX67N5B6BK",
                            Email = "administracija@stf.viko.lt",
                            Name = "Statybos fakultetas",
                            ShortName = "STF"
                        },
                        new
                        {
                            Id = "01J97HWA490JPD7AETH8AH0X09",
                            Email = "info@spf.viko.lt",
                            Name = "Sveikatos priežiūros fakultetas",
                            ShortName = "SPF"
                        },
                        new
                        {
                            Id = "01J97HWA49EE3YS886FKZK3SS1",
                            Email = "administracija@tef.viko.lt",
                            Name = "Technikos fakultetas",
                            ShortName = "TEF"
                        },
                        new
                        {
                            Id = "01J97HWA49RZY8G562XYC9A0PS",
                            Email = "administracija@vvf.viko.lt",
                            Name = "Verslo vadybos fakultetas",
                            ShortName = "VVF"
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Lecturer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanSubjectId")
                        .HasColumnType("text");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PlanSubjectId");

                    b.HasIndex("PositionId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.PlanSubject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("text");

                    b.Property<double>("ConsultationCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("CourseWorkHoursCount")
                        .HasColumnType("double precision");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("text");

                    b.Property<string>("EvaluationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ExamHours")
                        .HasColumnType("double precision");

                    b.Property<double>("FinalProjectExamCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("GradingHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("GradingNumberCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeworkHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("LectureHours")
                        .HasColumnType("double precision");

                    b.Property<int>("LecturesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("OtherContactHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("OtherNonContactCount")
                        .HasColumnType("double precision");

                    b.Property<string>("PlanId")
                        .HasColumnType("text");

                    b.Property<double>("PracticeHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("PracticeReportHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemoteLectureHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemotePracticeHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemoteTeachingHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("SelfStudyHours")
                        .HasColumnType("double precision");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("StudyProgramId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubGroupsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PlanId");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("PlanSubjects");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.PlannedGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("LabelName")
                        .HasColumnType("text");

                    b.Property<string>("LecturerId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OtherType")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("StudyProgramId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubGroupCount")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("1");

                    b.Property<int?>("Vf")
                        .HasColumnType("integer");

                    b.Property<int?>("Vnf")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("PlannedGroups");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Pab")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = "01J97HWA49F8WKHRFAFVKGM5YW",
                            Description = "Profesorius",
                            Name = "Profesorius_23",
                            Pab = 2.4199999999999999
                        },
                        new
                        {
                            Id = "01J97HWA49M3H7KXA6YKM8B7R3",
                            Description = "Docento, turinčio mokslo daktaro laipsnį",
                            Name = "Docentas_23",
                            Pab = 2.02
                        },
                        new
                        {
                            Id = "01J97HWA49C9PRSG4MKKSFTTET",
                            Description = "Docento, pripažinto menininko, o taip pat AT pritarimu vieneriems metams priimamam asmeniui, turinčiam didelę praktinę patirtį dėstomo dalyko srityje ir magistro kvalifikacinį laipsnį ar jam prilygintą aukštojo mokslo kvalifikaciją",
                            Name = "Docentas_menininkas_23",
                            Pab = 1.77
                        },
                        new
                        {
                            Id = "01J97HWA49EXGSMDX6EE4P3XW4",
                            Description = "Lektoriaus, turinčio mokslo daktaro laipsnį",
                            Name = "Lektorius dr._23",
                            Pab = 1.72
                        },
                        new
                        {
                            Id = "01J97HWA49CCRE6V4KE9JQ01Z0",
                            Description = "Lektorius",
                            Name = "Lektorius_23 (d)",
                            Pab = 1.6000000000000001
                        },
                        new
                        {
                            Id = "01J97HWA490R90XCQQ55Y4RYWD",
                            Description = "Lektorius",
                            Name = "Lektorius_23 (m)",
                            Pab = 1.4299999999999999
                        },
                        new
                        {
                            Id = "01J97HWA49YPGNGCGSVMJ1B26Y",
                            Description = "Asistento, turinčio magistro laipsnį",
                            Name = "Asistentas_23 (mag.)",
                            Pab = 1.3300000000000001
                        },
                        new
                        {
                            Id = "01J97HWA49XQQ22699GK57GZ3X",
                            Description = "Asistento, turinčio bakalauro arba profesinio bakalauro laipsnį",
                            Name = "Asistentas_23 (bak.)",
                            Pab = 1.3100000000000001
                        },
                        new
                        {
                            Id = "01J97HWA49J79HSRK0Q7SP11EX",
                            Description = "Profesorius",
                            Name = "Profesorius_24",
                            Pab = 2.4199999999999999
                        },
                        new
                        {
                            Id = "01J97HWA49FDARYAG0CWJD2P1Y",
                            Description = "Kviestinis profesorius",
                            Name = "Profesorius_Kv_24",
                            Pab = 2.4199999999999999
                        },
                        new
                        {
                            Id = "01J97HWA49PN932PCJ8227D0ZX",
                            Description = "Docentas",
                            Name = "Docentas_24",
                            Pab = 2.02
                        },
                        new
                        {
                            Id = "01J97HWA49RSMR7Q8H7DB6H63V",
                            Description = "Kviestinis docentas",
                            Name = "Docentas_Kv_24",
                            Pab = 2.02
                        },
                        new
                        {
                            Id = "01J97HWA49FX448PWKH9PN7BWK",
                            Description = "Asistentas",
                            Name = "Asistentas_24",
                            Pab = 1.8400000000000001
                        },
                        new
                        {
                            Id = "01J97HWA49G8AYGP1Q7T3APX34",
                            Description = "Jaunesnysis asistentas",
                            Name = "Jaunesnysis asistentas_24",
                            Pab = 1.78
                        },
                        new
                        {
                            Id = "01J97HWA496JJTQC203V8ACVYH",
                            Description = "Vyresnysis lektorius",
                            Name = "Vyresnysis lektorius_24",
                            Pab = 1.72
                        },
                        new
                        {
                            Id = "01J97HWA49VF1MSBATYDDAE6YR",
                            Description = "Lektorius",
                            Name = "Lektorius_24",
                            Pab = 1.6000000000000001
                        },
                        new
                        {
                            Id = "01J97HWA490ZQ735SWMG7TH9FT",
                            Description = "Dėstytojas praktikas",
                            Name = "Dėstytojas praktikas_24",
                            Pab = 1.72
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.StudyProgram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StudyType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("StudyPrograms");

                    b.HasData(
                        new
                        {
                            Id = "01J97HWA49BZR300SSS08VWRHB",
                            DepartmentId = "01J97HWA49EE1YW3XQJ9924XKW",
                            Name = "Programinės įrangos testavimas",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J97HWA49W40DJ0AMHEAH2BZF",
                            DepartmentId = "01J97HWA49MJ8GASEX9J85VVZ3",
                            Name = "Elektronikos inžinerija",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J97HWA494YGVW01RY2K2DCTE",
                            DepartmentId = "01J97HWA49MJ8GASEX9J85VVZ3",
                            Name = "Elektronikos inžinerija",
                            StudyType = 2
                        },
                        new
                        {
                            Id = "01J97HWA497ZKR7WHRRB8GKPNF",
                            DepartmentId = "01J97HWA49EV807R1NRT2W729H",
                            Name = "Informacijos sistemos",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J97HWA49BBNZJT8QB5PWCFMT",
                            DepartmentId = "01J97HWA49EV807R1NRT2W729H",
                            Name = "Informacijos sistemos",
                            StudyType = 2
                        },
                        new
                        {
                            Id = "01J97HWA494V24T07TFMC703TR",
                            DepartmentId = "01J97HWA49EV807R1NRT2W729H",
                            Name = "Informacijos sistemos",
                            StudyType = 3
                        },
                        new
                        {
                            Id = "01J97HWA49Q9D3KP8BE3QEQ494",
                            DepartmentId = "01J97HWA49MJ8GASEX9J85VVZ3",
                            Name = "Kompiuterių inžinerija",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J97HWA49NEND8N995K3RKS40",
                            DepartmentId = "01J97HWA49MJ8GASEX9J85VVZ3",
                            Name = "Kompiuterių inžinerija",
                            StudyType = 2
                        },
                        new
                        {
                            Id = "01J97HWA49HV2GYW8PMCVQA0KJ",
                            DepartmentId = "01J97HWA49EE1YW3XQJ9924XKW",
                            Name = "Programų sistemos",
                            StudyType = 1
                        },
                        new
                        {
                            Id = "01J97HWA49B0CG56WXYEWZ5JWE",
                            DepartmentId = "01J97HWA49EE1YW3XQJ9924XKW",
                            Name = "Programų sistemos",
                            StudyType = 4
                        },
                        new
                        {
                            Id = "01J97HWA493XF3FA4229KV0KVH",
                            DepartmentId = "01J97HWA49EE1YW3XQJ9924XKW",
                            Name = "Programų sistemos",
                            StudyType = 2
                        },
                        new
                        {
                            Id = "01J97HWA494K24Z9WZGBVZKCDZ",
                            DepartmentId = "01J97HWA49EE1YW3XQJ9924XKW",
                            Name = "Programų sistemos",
                            StudyType = 3
                        });
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("text");

                    b.Property<double>("ConsultationCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("CourseWorkHoursCount")
                        .HasColumnType("double precision");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("text");

                    b.Property<string>("EvaluationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ExamHours")
                        .HasColumnType("double precision");

                    b.Property<double>("FinalProjectExamCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("GradingHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("GradingNumberCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeworkHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("LectureHours")
                        .HasColumnType("double precision");

                    b.Property<int>("LecturesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("OtherContactHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("OtherNonContactCount")
                        .HasColumnType("double precision");

                    b.Property<double>("PracticeHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("PracticeReportHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemoteLectureHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemotePracticeHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemoteTeachingHoursCount")
                        .HasColumnType("double precision");

                    b.Property<double>("SelfStudyHours")
                        .HasColumnType("double precision");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("StudyProgramId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubGroupsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("LecturerSubject", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Lecturer", null)
                        .WithMany()
                        .HasForeignKey("LecturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyPlannerSoft.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Department", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Lecturer", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Department", "Department")
                        .WithMany("Lecturers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyPlannerSoft.Entities.PlanSubject", null)
                        .WithMany("Lecturers")
                        .HasForeignKey("PlanSubjectId");

                    b.HasOne("StudyPlannerSoft.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.PlanSubject", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Department", "Department")
                        .WithMany("PlanSubjects")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("StudyPlannerSoft.Entities.Plan", "Plan")
                        .WithMany("PlanSubjects")
                        .HasForeignKey("PlanId");

                    b.HasOne("StudyPlannerSoft.Entities.StudyProgram", "StudyProgram")
                        .WithMany("PlanSubjects")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Plan");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.PlannedGroup", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Lecturer", "Lecturer")
                        .WithMany("PlannedGroups")
                        .HasForeignKey("LecturerId");

                    b.HasOne("StudyPlannerSoft.Entities.StudyProgram", "StudyProgram")
                        .WithMany("PlannedGroups")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.StudyProgram", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Department", "Department")
                        .WithMany("StudyPrograms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Subject", b =>
                {
                    b.HasOne("StudyPlannerSoft.Entities.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("StudyPlannerSoft.Entities.StudyProgram", "StudyProgram")
                        .WithMany("Subjects")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Department", b =>
                {
                    b.Navigation("Lecturers");

                    b.Navigation("PlanSubjects");

                    b.Navigation("StudyPrograms");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Lecturer", b =>
                {
                    b.Navigation("PlannedGroups");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.Plan", b =>
                {
                    b.Navigation("PlanSubjects");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.PlanSubject", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("StudyPlannerSoft.Entities.StudyProgram", b =>
                {
                    b.Navigation("PlanSubjects");

                    b.Navigation("PlannedGroups");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
